language: node_js
node_js:
  - "8"

services:
  - docker

#install:
#  - docker run -it frumania/uiveri5-base:latest bash
 
#before_script:
#  - npm install

script:
  - ls -l
  - pwd
  - docker run --name myslave -v $PWD:/test/ -dit frumania/uiveri5-base:latest /bin/bash
  - docker ps
  - sleep 10
  - docker ps
  - docker exec -d myslave /opt/selenium/startSeleniumServer.sh
  - docker exec myslave ls
  - docker exec myslave bash -c "cd /test/test && visualtest --v --seleniumAddress http://localhost:4444/wd/hub --config '{"auth": {"sapcloud-form": {"user": "info@frumania.com","pass": "J#6i/{%lY+]."}}'"
  - docker exec myslave bash -c "cd /test/test && visualtest --v --config '{"auth": {"sapcloud-form": {"user": "$user","pass": "$password"}}'"