language: node_js
node_js:
  - "8"

services:
  - docker

#install:
#  - docker run -it frumania/uiveri5-base:latest bash
 
#before_script:
#  - npm install

script:
  - docker run --name myslave -it frumania/uiveri5-base:latest bash
  - exit
  - docker ps
  - sleep 30
  - docker ps
  - docker exec -d myslave sh -c "echo a && echo b"
  - docker exec -d myslave visualtest --v