language: node_js
node_js:
  - "8"

services:
  - docker

#install:
#  - docker run -it frumania/uiveri5-base:latest bash
 
#before_script:
#  - npm install

script:
  - ls -l
  - pwd
  - docker run --name myslave -e user=$user -e password=$password -v $PWD:/test/ -dit frumania/uiveri5-base:latest /bin/bash
  - docker ps
  - sleep 10
  - docker ps
  - docker exec -d myslave /opt/selenium/startSeleniumServer.sh
  - sleep 10
  - docker exec myslave bash -c "cd /test/test && ./test1.sh"
  - docker exec myslave bash -c "cd /test/test && ./test2.sh"