language: node_js
node_js:
  - "8"

services:
  - docker

#install:
#  - docker run -it frumania/uiveri5-base:latest bash
 
#before_script:
#  - npm install

script:
  - docker run --name myslave -dit frumania/uiveri5-base:latest /bin/bash
  - docker ps
  - sleep 10
  - docker ps
  - docker exec -d myslave /opt/selenium/startSeleniumServer.sh
  # Copy Test?!
  - docker exec myslave visualtest --v --seleniumAddress http://localhost:4444/wd/hub
  - docker exec myslave visualtest --v