language: node_js
node_js:
  - "8"

services:
  - docker

#install:
#  - docker run -it frumania/uiveri5-base:latest bash
 
#before_script:
#  - npm install

script:
  - docker run -it frumania/uiveri5-base:latest bash
  - sleep 10
  - visualtest --v